# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: alejandr0pg
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: test-polygon-aws
service: serverless-polygon-test

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
